config/routes.rb
Rails.application.routes.draw do

  namespace :vendors do
    get 'tires/new'
  end

  namespace :vendors do
    get 'tires/edit'
  end

  root 'vendors#index'

  resources :vendors do
    collection do
      get :search_by_tire
      get :search_by_car
      get :order_price
      get :order_rate
      get :admin
    end
    resources :tires
  end

  get 'pages/about'
  get 'pages/authenticate'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tire.rb
class Tire < ApplicationRecord
  belongs_to :vendor
  validates :brand, :model, presence: true
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :tires

  validates :address, :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def deals
  end
end

app/controllers/tires_controller.rb
class TiresController < ApplicationController
  def new
    @tire = Tire.new
  end

  def create
    @vendor = Vendor.find(params[:vendor_id])
    @tire = @vendor.tires.create(tire_params)
    if @tire.save
      redirect_to vendor_path(@vendor)
    else
      render '_error'
      end

  end

  def error
    @vendor = Vendor.find(params[:vendor_id])
    @tire = @vendor.tires.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:vendor_id])
    @tire = @vendor.tires.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:vendor_id])
    @tire = @vendor.tires.find(params[:id])

    if @tire.update(tire_params)
      redirect_to vendor_path(@vendor)
    else
      render 'edit'
    end
  end

  def destroy
    @vendor = Vendor.find(params[:vendor_id])
    @tire = @vendor.tires.find(params[:id])
    @tire.destroy
    redirect_to vendor_path(@vendor)
  end

  def show
    @tire = Tire.find(params[:id])
  end


  private
  def tire_params
    params.require(:tire).permit(:model, :brand, :price, :quantity)
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_filter :disable_layout, only: [:order_rate, :order_price]

  http_basic_authenticate_with name: "marie", password: "yamanakasawao",
  except: [:index, :search_by_tire, :search_by_car, :order_rate, :order_price]

  def index
  end

  def admin
    @vendors = Vendor.all
  end

  def error
    @vendor = Vendor.find(params[:id])
  end

  def new
    @vendor = Vendor.new
    @vendor = Vendor.find(params[:id])
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to vendor_path @vendor
    else
      render '_error'
    end
  end

  def update
    @vendor = Vendor.find(params[:id])

    if @vendor.update(vendor_params)
      redirect_to @vendor
    else
      render 'edit'
    end
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def destroy
    @vendor= Vendor.find(params[:id])
    @vendor.destroy

    redirect_to admin_vendors_path
  end

  def show
    @vendor = Vendor.find(params[:id])
    @vendor_tires = @vendor.tires.all
  end

  def search_by_tire
  end

  def search_by_car
  end

  def order_rate

  end

  def order_price

  end

  private

  def disable_layout
    render layout: false
  end

  def vendor_params
    params.require(:vendor).permit(:name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tires_helper.rb
module TiresHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TireChaser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header clearfix">
        <p class="text-muted">TIRE CHASER</p>
        <ul class="topnav" id="myTopnav">
          <li><%= link_to 'Home', vendors_path %></li>
          <li><%= link_to 'Deals', pages_about_path%></li>
          <li><%= link_to 'Contact', pages_about_path%></li>
          <li><%= link_to 'About', pages_about_path%></li>
          <li class="icon">
            <a href="javascript:void(0);" onclick="myFunction()">&#9776;</a>
          </li>
        </ul>
      </div>
    </div><!-- /container -->
    <%= yield %>
    <footer class="footer">
      <p>&copy; 2016 Media Moolah LLC</p>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<%= link_to 'Home', vendors_path %>

app/views/tires/_error.html.erb
<%= form_for([@vendor, @vendor.tires.new]) do |tire| %>

    <% if @tire.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tire.errors.count, "error") %> prohibited this vendor from being generated:
          </h2>
          <ul>
            <% @tire.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
          <%= render 'form' %>
          <%= link_to 'Back', vendor_path(@vendor), class: 'btn btn-lg btn-success'%>
        </div>
    <% end %>
<% end %>

app/views/tires/_form.html.erb
<%= form_for([@vendor, @vendor.tires.build]) do |tire| %>
    <%= tire.label :brand %>
    <br />
    <%= tire.text_field :brand %>
    <br />
    <%= tire.label :model %>
    <br />
    <%= tire.text_field :model %>
    <br />
    <%= tire.label :price%>
    <br />
    <%= tire.number_field :price, class: :text_field, step: :any %>
    <br />
    <%= tire.label :quantity%>
    <br />
    <%= tire.number_field :quantity %>
    <br />
    <%= tire.submit %>
<% end %>

app/views/tires/edit.html.erb
<div id="tireedit">
<h2>Edit Tire Entry</h2>

<%= form_for :tire, url: vendor_tire_path(@vendor), method: :patch do |f| %>

    <% if @tire.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tire.errors.count, "error") %> prohibited
            this tire entry from being saved:
          </h2>
          <ul>
            <% @tire.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :model %>
      <br/>
      <%= f.text_field :model %>
      <br/>
    </p>

    <p>
      <%= f.label :brand%>
      <br/>
      <%= f.text_field :brand %>
      <br/>
    </p>

    <p>
      <%= f.label :price%>
      <br/>
      <%= f.number_field :price, class: :text_field, step: :any %>
      <br/>
    </p>
    <p>
      <%= f.label :quantity%>
      <br/>
      <%= f.number_field :quantity %>
      <br/>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', vendor_path(@vendor), class: 'btn btn-lg btn-success'%>
</div>

app/views/vendors/_error.html.erb
<%= form_for Vendor.new do |vendor| %>

    <% if @vendor.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being generated:
          </h2>
          <ul>
            <% @vendor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
          <%= render 'new' %>
    <% end %>
<% end %>

app/views/vendors/_new.html.erb
<div id="newvenform">
<%= form_for Vendor.new do |vendor| %>

    <%= vendor.label :name %>
    <br />
    <%= vendor.text_field :name %>
    <br />
    <%= vendor.label :address %>
    <br />
    <%= vendor.text_field :address %>
    <br />
    <%= vendor.submit %>
<% end %>
</div>

app/views/vendors/admin.html.erb
<div id="adminwrapper">
  <div id='new_vendor'>
    <p>Create new vendor:</p>
    <%= render 'new' %>
  </div>

  <div id='vendor_list'>
    <table>
      <tr>
        <th>Vendor&nbspID</th>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>

      <% @vendors.each do |h| %>
          <tr>
            <td><%= h.id %></td>
            <td><%= h.name %></td>
            <td><%= link_to 'Show', vendor_path(h) %></td>
            <td><%= link_to 'Edit', edit_vendor_path(h) %></td>
            <td><%= link_to 'Delete', vendor_path(h),
                            method: :delete,
                            data: { confirm: 'Are you sure you want to delete this vendor and their associated tire records?' } %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/vendors/edit.html.erb
<div id="vendoredit">
<%= form_for :vendor, url: vendor_path(@vendor), method: :patch do |f| %>

    <% if @vendor.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@vendor.errors.count, "error") %> prohibited
            this vendor page from being saved:
          </h2>
          <ul>
            <% @vendor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name%><br>
      <%= f.text_field :name%>
    </p>

    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', admin_vendors_path, class: 'btn btn-lg btn-success'%>
</div>

app/views/vendors/index.html.erb
<div id="jbwrapper">
  <div class="jumbotron" id="jbCar">
    <div id="jbContainer">
      <p>Search for Tires by Car</p><br>
      <select name="carmaker" autocomplete="off">
       <option value="null" selected>Select Brand</option>
       <option value="null">Maserati</option>
     </select><br><br>
     <select name="model" autocomplete="off">
      <option value="null" selected>Select Model</option>
      <option value="null">GranTurismo</option>
    </select>
  </div>
    <%= link_to 'Search', search_by_car_vendors_path, class: 'btn btn-lg btn-success' %>
  </div>
</div>

<div id="portal">
    <%= link_to 'Portal', admin_vendors_path %>
</div>

app/views/vendors/order_price.html.erb
<div class="bracket" id="cdtire">
  <%= image_tag 'cdtire.jpg'%>
  <p>$179.98</p>
  <div class='clearfix'></div>
</div>
<div class="bracket" id="terraza">
  <%=image_tag 'terraza.jpg'%>
  <p>$184.99</p>
  <div class='clearfix'></div>
</div>
<div class="bracket" id="trevino">
  <%= image_tag 'trevino.jpg'%>
  <p>$204.99</p>
  <div class='clearfix'></div>
</div>
<div class="bracket" id="lara">
  <%= image_tag 'lara.jpg'%>
  <p>$219.95</p>
  <div class='clearfix'></div>
</div>

app/views/vendors/order_rate.html.erb
<div class="bracket" id="cdtire">
  <%= image_tag 'cdtire.jpg' %>
  <p>$179.98</p>
</div>
<div class="bracket" id="trevino">
  <%= image_tag 'trevino.jpg' %>
  <p>$204.99</p>
</div>
<div class="bracket" id="terraza">
  <%= image_tag 'terraza.jpg' %>
  <p>$184.99</p>
</div>
<div class="bracket" id="lara">
  <%= image_tag 'lara.jpg' %>
  <p>$219.95</p>
</div>

app/views/vendors/search_by_car.html.erb
<!-- Jumbotron -->
<div>
  <div class="jumbotron">
    <div class="jumbotronText">
      <h2>Maserati GranTurismo</h2>
      <p>Inspired by the Maserati Birdcage 75th concept car, the GranTurismo is a magnificent example of gorgeous styling and brilliant engineering.</p>
    </div>
  </div>
  <!-- end of Jumbotron -->
<div id="tireSearch">
  <b>Brand: </b>
  <select name="tirebrand" autocomplete="off">
  <option value="null" selected>Select Brand...</option>
  <option value="null">Michelin</option>
  </select>
    <b>Feature: </b>
    <select name="type" autocomplete="off">
    <option value="null" selected>Select Type...</option>
    <option value="null">Performance</option>
    </select>
  <b>Size: </b>
  <select name="size1" autocomplete="off">
   <option value="null" selected>Select Size</option>
   <option value="null">205</option>
 </select>
 <select name="size2" autocomplete="off">
  <option value="null" selected>Select Size</option>
  <option value="null">55</option>
</select>
<select name="size3" autocomplete="off">
 <option value="null" selected>Select Size</option>
 <option value="null">15</option>
</select><br>
</div>
<div id="thebutton">
  <%= link_to 'Search', search_by_tire_vendors_path, class: 'btn btn-lg btn-success'%>
</div>

app/views/vendors/search_by_tire.html.erb
<div id="topContainer" class="clearfix">
  <div id="list">
    <!-- Populated on #quality_select change -->
  </div>
  <div id="profile" class="clearfix">
    <div id=" pics">
    <%= image_tag 'tireprofile.jpg' %>
    <%= image_tag 'wall.jpg' %>
    </div>
    <div id="words">
      <p>Brand: Michelin</p>
      <p>Model: Pilot Sport A/S 3+</p>
      <p>Type: Performance/Sport</p>
      <p>Dimensions: 205 x 55 x 15</p>
    </div>
  </div>
</div>

<br>

<div id="dropdowns">
  <p>Sort by:</p>

  <select id="quality_select" name="quality" autocomplete="off">
    <option default value="rate" selected>Shop Rating</option>
    <option value="price">Lowest Price</option>
  </select>

  <select name="distance" autocomplete="off">
    <option value="null" selected>Within...</option>
    <option value="null">5 mi.</option>
  </select>
</div>

<br>

<div id="map">
  <%= image_tag 'map.jpg' %>
</div>

app/views/vendors/show.html.erb
<div id = 'vendorlayout'>

  <div id= 'vendorinfo'>

  <h2>Name:</h2>
  <p><%= @vendor.name %></p>
  <br />
  <h2>Address:</h2>
  <p><%= @vendor.address %></p>
  </div>

  <div id='new_tire'>
    <h2>Create New Tire</h2>
    <%= render '/tires/form.html.erb' %>
  </div>

  <div = 'inventory'>
  <h2>Inventory</h2>
      <table id="invtab">
        <tr>
          <td>Tire ID</td>
          <td>Maker</td>
          <td>Model</td>
          <td>Price</td>
          <td>Stock</td>
          <td colspan="2"></td>
        </tr>
        <% @vendor_tires.each do |h| %>
      <tr>
        <td><%= h.id %></td>
        <td><%= h.brand %></td>
        <td><%= h.model %></td>
        <td><%= h.price %></td>
        <td><%= h.quantity %></td>
        <td>
          <%= link_to 'Edit', edit_vendor_tire_path(@vendor.id, h.id) %>
          &nbsp
          <%= link_to 'Delete', vendor_tire_path(@vendor.id, h.id),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this tire record?' } %></td>
      </tr>
        <% end %>
      </table>
  </div>
</div>
<p id = 'backbutton'>
  <%= link_to 'Back', admin_vendors_path, class: 'btn btn-lg btn-success'%>
</p>